project_id = "etabpbfokzhhfuybeieu"

[functions.validate-invitation]
verify_jwt = false

[functions.scan-board]
verify_jwt = false

[functions.scan-competition-photo]
verify_jwt = true

[functions.analyze-stock-images]
verify_jwt = true
